Задание 1

    Создайте матрицу 3 на 3, заполненную числами от 1 до 9
    Прибавьте к ней матрицу с единицами на диагонале
    Умножьте полученную матрицу на вектор (1, 2, 3)
    Вычислить транспонированную матрицу А от полученной в результате прибавления матрицы 
    Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
import numpy as np

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix = matrix + np.eye(3,3)
matrix

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
vec = np.array([1, 2, 3])
matrix.dot(vec)

array([15., 34., 53.])

In [ ]:
matrix.T

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
np.linalg.inv(matrix)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])


Задание 2

Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
              
print(m)

In [ ]:
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [ ]:
np.linalg.eig(m)

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!


In [ ]:
new = np.array([[1,2],[1,3]])
new1 = np.array([[5,4],[3.5,3]])

In [ ]:
print(np.linalg.det(new))
print(np.linalg.det(new1))

1.0
0.9999999999999987
